### ISSUE TITLE
pebble upgrade

### ISSUE THREAD

**Issue by NoamGaloz1** [jupyterhub/pebble-helm-chart#33]
### Proposed change

I would like to ask you to upgrade the pebble app version since they released a new one with updated go versions, 2 weeks ago.

### Who would use this feature?

Everyone uses your chart

**Comment by consideRatio** [comment]
Pebble 2.3.1 is now upgraded to 2.5.1, and this is made available in pebble helm chart version 1.1.0 - thanks for opening this issue @NoamGaloz1!
